### PR TITLE
Add support for redis cluster

### PR DESCRIPTION
**Pull request by Dominik48N**
I once expanded the Redis support so that you can also use messaging with a Redis cluster.

I only made `addresses` from the `adress` in the config and a string list where you can specify the IP addresses and ports of your Redis nodes.

### CODE REVIEW

**Comment by lucko** [comment]
I'm happy to merge this change in, but it needs to be backwards compatible please! (people's existing config files should keep working as they did before)

**Comment by Dominik48N** [comment]
Do you think it makes more sense to create another config key for the multiple addresses or that I offer support for a string & a string list from the old config entry?

**Comment by powercasgamer** [comment]
> Do you think it makes more sense to create another config key for the multiple addresses or that I offer support for a string & a string list from the old config entry?

Should check if `address` exists and use that (and possibly migrate that to `addresses`), if it doesn't exists use `addresses`

**Comment by Dominik48N** [comment]
I changed something. Does that correspond to such an idea?

**Comment by lucko** [comment]
Yep much better, can we keep the config how it was before? (most people I assume will only be using a single instance)

**Comment by Dominik48N** [comment]
Do you mean that in the default config there is only `address` instead of `addresses` and that `addresses` then only says in the wiki that this is available?

**Comment by lucko** [comment]
Yea :)

**Comment by Dominik48N** [comment]
I'll do it for you right away. But I also write that in the comment above the section so that you can read it directly in the config that you can add multiple nodes.

**Comment by Dominik48N** [comment]
Is now back with before!

**Comment by lucko** [comment]
The unit/integration tests are failing, I think probably just an import that needs to be updated in the standalone module

**Comment by Dominik48N** [comment]
The old Jedis version doesn't include some features that I used. I think it was because of that.

**Comment by lucko** [comment]
That's fine, you'll also need to update this file https://github.com/LuckPerms/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java

and run the DependencyChecksumTest to figure out the new hash

**Comment by Dominik48N** [comment]
I have adjusted.
I tested it on Velocity 3.2.0-SNAPSHOT and Paper 1.19.4 with two Redis Nodes (7.0.11).

**Comment by Dominik48N** [comment]
I can not understand. My tests pass at my place?

**Comment by Dominik48N** [comment]
I refresh my whole local project. I'm very confused right now, sorry.

**Comment by lucko** [comment]
By default the docker integration tests are skipped, try commenting out this line

https://github.com/LuckPerms/LuckPerms/blob/master/standalone/src/test/java/me/lucko/luckperms/standalone/MessagingIntegrationTest.java#L56

and running the redis test :)

**Comment by Dominik48N** [comment]
Sorry, I've been looking for the problem all this time.
I didn't consider that normal Redis instances logically don't work in a cluster.

Since the cluster support is also disabled in the test, the test (fortunately) does not pass. Since I tested it in a Redis cluster, I was always wondering why it works for me. I'll work on it and add additional support for it when cluster support is disabled.

**Comment by lucko** [comment]
No problem - the tests did their job then! :)

**Comment by Dominik48N** [comment]
The tests pass and now it also works for non-Redis cluster setups. I also tested it again myself, for single node setups, with the latest Redis Docker Version, Velocity 3.2.0-SNAPSHOT and Paper 1.19.4.

Please have a look again 👍

image

**Review by powercasgamer — CHANGES_REQUESTED** [review]

**Review by powercasgamer — APPROVED** [review]

**Comment by lucko** [comment]
Turns out there is a new version of `JedisPool` called `JedisPooled` which implements a common interface to `JedisCluster`, which makes things a bit tidier I think :)

I've re-ran the tests and everything looks good! Thanks for the PR :)

**Pull request merged**
