### PR TITLE
Update Fabric to 1.20.2

### PR DESCRIPTION
**Pull request by Aurelien30000**
Hello, this pull request adds the support for Fabric 1.20.2.
*You can try it! Please let me know if you have any issues with the following version :D*

[LuckPerms-Fabric-5.4.102.zip](https://github.com/LuckPerms/LuckPerms/files/12708942/LuckPerms-Fabric-5.4.102.zip)

### CODE REVIEW

**Comment by lucko** [comment]
I'm sorry, I didn't see this!

**Comment by MCMDEV** [comment]
@Aurelien30000 Can you re-open the PR? I'd like 1.20.2 support very much.

**Comment by LeotomasMC** [comment]
@MCMDEV this commit adds fabric 1.20.2 support. no reason to reopen a pr that adds something that is already supported
https://github.com/LuckPerms/LuckPerms/commit/331a3287714956df9b03bc836e0138acd0e0f867

**Comment by MCMDEV** [comment]
> @MCMDEV this commit adds fabric 1.20.2 support. no reason to reopen a pr that adds something that is already supported [331a328](https://github.com/LuckPerms/LuckPerms/commit/331a3287714956df9b03bc836e0138acd0e0f867)

I seemed to have missed that.

**Pull request closed without merging**
