### PR TITLE
Added redis authentication with username

### PR DESCRIPTION
**Pull request by EduardWayland**
Hi!
I'm going straight to the point: the current version of LuckPerms has just a password field for Redis authentication which limits the setup to a default username auth system which not always is the best option for security purposes. Then I decided to open this pull request to implement an optional username field which enables the authentication through username too. I have tried the new feature before opening this PR to test it and everything seems working correctly.

### CODE REVIEW

**Comment by lucko** [comment]
Looks really great - thanks! but do you think you could cleanup the whitespace changes? :)

**Comment by EduardWayland** [comment]
Glad to see you like it. Regarding whitespace changes: do you mean the tab indents on blank lines?

**Comment by Turbotailz** [comment]
You've deleted some blank lines which I guess Luck would prefer to keep
image

**Comment by Turbotailz** [comment]
Oh nvm I didn't see the latest commit lol

**Comment by lucko** [comment]
> Glad to see you like it. Regarding whitespace changes: do you mean the tab indents on blank lines?

Yep those! and also the changes to the imports :)

**Comment by EduardWayland** [comment]
Ok, I think I've added all the blank lines back. I don't know if you have posted it already anywhere, but I think it would be really helpful have your code style configuration uploaded somewhere, all these changes "I did" were basically done by the default IntelliJ IDEA code-style config. I may like to PR more things in the future and having your code-style will avoid the need of those micro adjustments, even if you just send it privately to me, that would be really appreciated.

**Comment by lucko** [comment]
Looks great, thank you :)

**Comment by lucko** [comment]
On the topic of auto-formatters, my personal suggestion would be to disable them entirely when you're working on other people's projects, and be sure to review the diffs in the files you're editing before you commit. I find that generally there's much less friction that way. :)

However, I'm happy to share my IntelliJ config if that would be useful.
https://gist.github.com/lucko/be4287a2b08821f2a608d25ea16124c1

**Pull request merged**
