### PR TITLE
Minestom Support

### PR DESCRIPTION
**Pull request by HEROOSTECH**
It's time for it... Minestom LuckPerms. It's made by LeoDog896 (He allowed for me to create pr), i just updated it to latest minestom. This use minestom permission system and doesn't override hasPermission method, because minestom currently doesn't allow to do this (it's possible to add PlayerProvider, but most of servers will use custom PlayerProvider). Sorry for my bad English btw.

### CODE REVIEW

**Comment by LeoDog896** [comment]
I haven't worked on Minestom in a while, but I am absolutely willing to help smoothen the process on adding Minestom to LuckPerms. I *think* I talked about this with lucko quite a while ago, and since then the Minestom API is much more stable.

**Comment by HEROOSTECH** [comment]
I completed this, i used some classes from dev-hydrogen's luckperms. Currently to update permissions for player - player has to rejoin. If you tell me how to listen to update permissions event, i can open new pr (if you merge this).

**Comment by HEROOSTECH** [comment]
Ignore higher comment, i fixed this, permissions have worked, but i forgot to call player.refreshCommands().

**Comment by dev-hydrogen** [comment]
I dont exactly appreciate that my commits are being used in this PR in another persons name. This pull request should just include the commits directly from the project-cepi (as well as my) repositories.

That also ignores the issue that the way this works is at best untested, and at worst unstable. How i made my fork work, is that it (tries) to sync up permissions between luckperms and minestom when the player join, and then listens to the luckperms api to sync any changes that happen after that. This approach doesnt allow for any nice-to-haves like wildcard support, as that would mean needing to override hasPermission, which currently is not possible on minestom. 

Theres a reason i never made a pull request from my fork, I don't trust it enough to be used anywhere other than on my own servers.

**Comment by HEROOSTECH** [comment]
> I dont exactly appreciate the fact that my commits are being used in this PR in another persons name, as if this was somehow merged, i'd like the small piece of credit. This pull request should just include the commits directly from the project-cepi (as well as my) repositories.
> 
> That also ignores the issue that the way this works is at best untested, and at worst unstable. How i made my fork work, is that it (tries) to sync up permissions between luckperms and minestom when the player join, and then listens to the luckperms api to sync any changes that happen after that. This approach doesnt allow for any nice-to-haves like wildcard support, as that would mean needing to override hasPermission, which currently is not possible on minestom.
> 
> Theres a reason i never made a pull request from my fork, I don't trust it enough to be used anywhere other than on my own servers.

I agree somewhat, but I tested today and had no issues after all the commits.

**Comment by HEROOSTECH** [comment]
Then if you merge it - credit all Contributors (Me (I have did small changes too), LeoDog, dev-hydrogen)

**Comment by LeoDog896** [comment]
You should redo the PR with a proper git history then -- commits from me and hydrogen instead of just you.

**Comment by HEROOSTECH** [comment]
Because hydrogen wanna credit - #3521

**Pull request closed without merging**
